name: Auto-Sync Main to Guest-App

on:
  push:
    branches:
      - main

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Force Sync guest-app with main
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -B guest-app origin/main
          git push origin guest-app --force